# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt .

# Install any dependencies in the requirements.txt file
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set environment variable to specify S3 bucket dynamically in ECS
ENV S3_BUCKET="my-exchange-rate-html-bucket"

# Command to run the application
CMD ["python", "main.py"]
